spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: users
server:
  port: 8082